### ISSUE TITLE
Support JupyterLab 3

### ISSUE THREAD

**Issue by bollwyvl** [agoose77/jupyterlab-markup#11]
As of posting, JupyterLab 3 is still a [release candidate](https://pypi.org/project/jupyterlab/#history), but is a pretty compelling way forward, and already pretty easy to develop against `pip` or [`conda`](https://gist.github.com/bollwyvl/c2a5734ac23321d1d1af61ca4803cadc). As #10 adds a serverextension to handle the `.wasm` mime type junk, it would be a relatively small step to move to a `pip install`-and-there-you-go end user experience.

Some concrete steps on top of #10:
- migrate to a `jupyter_server` (vs `notebook`) extension... 
  - I haven't done this before, but it can't be _that_ different
- add the `labextension build` stuff, dumping into `src/jupyterlab_markup/static`
- redo the build plumbing
  - source the version (and other package information) only from `static/package.json`
  - I'm a fan of `doit` for keeping the package in a releasable state from a single package

Because a big part of #10 is to make this extensible, it would _still_ be important to do `npm` releases, so that others can get at the `Token` to make extensions with additional `markdown-it` plugins.

**Comment by agoose77** [comment]
@bollwyvl could you elaborate more on `doit` / suggest any resources for learning about it? I've seen it around, but never had hands on experience.

**Comment by agoose77** [comment]
Closing as most of this work has been done now :)
