### ISSUE TITLE
Binder url not working

### ISSUE THREAD

**Issue by MarcSkovMadsen** [agoose77/jupyterlab-markup#24]
![image](https://user-images.githubusercontent.com/42288570/117930953-e34f6280-b2fe-11eb-8ea8-16298b2d60c9.png)

![image](https://user-images.githubusercontent.com/42288570/117930751-ac794c80-b2fe-11eb-9f74-2fceaad7ed13.png)

**Comment by MarcSkovMadsen** [comment]
Changing `master` to `main` seems to solve the problem

https://mybinder.org/v2/gh/agoose77/jupyterlab-markup.git/main?urlpath=lab

**Comment by agoose77** [comment]
Thanks @MarcSkovMadsen, it's one of those bugs that's probably quite common these days!
