### ISSUE TITLE
Support for PlantUML

### ISSUE THREAD

**Issue by murata100** [agoose77/jupyterlab-markup#43]
Support for PlantUML
[markdown-it-plantuml](https://www.npmjs.com/package/@markspec/markdown-it-plantuml)

[markdown-it-markspec](https://www.npmjs.com/package/@markspec/markdown-it-markspec)

**Comment by agoose77** [comment]
Unfortunately, I don't think we can support this particular package, because it needs to run locally rather than in-browser.
