### ISSUE TITLE
Import error during development install

### ISSUE THREAD

**Issue by nagyj2** [agoose77/jupyterlab-markup#49]
I am trying to install jupyterlab-markup using the development steps at the bottom of the README but there is an error when importing 'StaticModule' from 'setuptools.config'. The error occurs when I run `pip install -e .` ([output log](https://github.com/agoose77/jupyterlab-markup/files/8391883/output.txt)). I am using Anaconda's Python 3.9.11 on MacOS 11.4 with a clean Anaconda virtual environment with only pip and jupyter installed. How can I fix this error?

**Comment by agoose77** [comment]
Normally I like to reply to bug reports within a couple of days. For some reason, I missed this one entirely.

Do you want to perform a development install? If not, you *should* be getting a wheel on PyPI if you use `pip install jupyterlab-markup.`

Assuming that you *do* want to build a development install, I can reproduce this. I've added 7e5d422 which should fix it. Note that trying to build an existing sdist from PyPI won't work, as I haven't published this fix to PyPI.
