### ISSUE TITLE
svgbob Code Fence Label inconsistent with sphinx-contrib/svgbob

### ISSUE THREAD

**Issue by psychemedia** [agoose77/jupyterlab-markup#57]
Hi

I notice that the code fence label for creating svgbob diagrams is `bob` whereas the label used in [`sphinx-contrib/svgbob`](https://github.com/sphinx-contrib/svgbob) is `svgbob`. It would be really useful if a common label were used particularly where notebooks are authored and previewed in JupyterLab/RetroLab and then rendered to Jupyter Book.

**Comment by agoose77** [comment]
Thanks for raising this! I'll look to adding a backwards compatible change, and recommend `svgbob`.

**Comment by agoose77** [comment]
Could you try https://pypi.org/project/jupyterlab-markup/2.0.0a0/ please?

**Comment by psychemedia** [comment]
The `svgbob` label seems to work fine and `bob` continues to work:

```` 

```bob
from -> to
```


```svgbob
from -> to
```
````

I note that `jupyterlab-imarkdown` and `jupyterlab-myst` expect `jupyterlab-markup~=1.0` so those projects may need maintenance following a version change.

**Comment by agoose77** [comment]
Fab. Certainly `jupyterlab-myst` will need updating. The 2.0.0 version splits the `diagrams` plugin into two separate plugins, which is a breaking change, so I've bumped the version.

`jupyterlab-imarkdown` isn't really intended for use, but I will probably update it anyway :)

**Comment by agoose77** [comment]
I'm closing this issue as this feature is in a downloadable release! 

Dependent projects will need to update, certainly.
