### ISSUE TITLE
Support for pythonic preprocessing

### ISSUE THREAD

**Issue by Amichayg** [agoose77/jupyterlab-markup#73]
Hi there, 
i would like to have the ability to extend the rendering functionality of the plugin using preexisting python libraries. 
Something similar to the feature in marked that lets you specify a python script to use to preprocess the text before rendering. 

I think the implementation could be another option in the settings to specify the python file to load, with options for pre/post processing. Code wise the inputted file will be executed in the server extension. This will enable some pretty cool hooks into the rendering process i think.

**Comment by agoose77** [comment]
`jupyterlab-markup` fundamentally operates in JS-land, with all Markdown processing happening in the frontend (browser). As such, there's no scope for any Python (pre)processing, which would limit `jupyterlab-markup` to requiring a kernel. In the long-long term, something like this would be possible with WASM extensions that would permit users to write Python that operates in-browser, but even then I can't see the merit over just writing TypeScript; MarkdownIt is complex.

If you want to pre-process Markdown, you can already create an `IPython.display.Markdown` object from a Python kernel, which `jupyterlab-markup` will then happily render.
